FROM node:latest AS development
ENV NODE_ENV development

# Add a work directory
WORKDIR /app

# Cache and install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install

# Copy app files
COPY . .

# Expose port
EXPOSE 3000

# Start app
CMD [ "npm", "start" ]
